# Generated by Django 3.1.1 on 2020-09-29 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gessol', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoicesInt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inv_number', models.CharField(max_length=20)),
                ('inv_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('vat_number', models.CharField(max_length=11)),
                ('cf_number', models.CharField(max_length=16)),
                ('address', models.CharField(max_length=100)),
                ('cap', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=100)),
                ('prov', models.CharField(max_length=10)),
                ('gg_valuta', models.IntegerField()),
                ('sds_path', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='AnaSupp',
        ),
        migrations.AddField(
            model_name='invoicesint',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gessol.supplier'),
        ),
    ]
