# Generated by Django 3.1.1 on 2020-09-29 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gessol', '0002_auto_20200929_1123'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChemProds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('solvent', models.BooleanField()),
                ('perc_solv', models.IntegerField()),
                ('wet_dep', models.BooleanField()),
                ('fin_dep', models.BooleanField()),
                ('notes', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Supplier',
            new_name='Suppliers',
        ),
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gessol.chemprods')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('perc_sov', models.IntegerField()),
                ('chem_prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gessol.chemprods')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gessol.invoicesint')),
            ],
        ),
        migrations.AddField(
            model_name='chemprods',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gessol.suppliers'),
        ),
    ]
