# Generated by Django 3.1.1 on 2020-09-29 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gessol', '0003_auto_20200929_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChemSubstances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('substance', models.CharField(max_length=200)),
                ('ec_number', models.CharField(max_length=30)),
                ('cas_number', models.CharField(max_length=30)),
                ('selected', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SvhcSubstances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('svhc_substance', models.CharField(max_length=200)),
                ('ec_number', models.CharField(max_length=30)),
                ('cas_number', models.CharField(max_length=30)),
                ('inclusion_date', models.DateField()),
                ('inclusion_reason', models.CharField(max_length=100)),
                ('decision_number', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='VatCode',
            fields=[
                ('vat_code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=10)),
                ('tax_perc', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.AddField(
            model_name='suppliers',
            name='vat_perc',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gessol.vatcode'),
        ),
    ]
