# Generated by Django 3.1.1 on 2020-09-30 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gessol', '0004_auto_20200929_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='HazardPictograms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pictogram', models.ImageField(upload_to='')),
                ('description', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='HazardStatements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('descritpion', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameModel(
            old_name='InvoicesInt',
            new_name='InvoiceHeaders',
        ),
        migrations.RenameModel(
            old_name='PriceList',
            new_name='PriceLists',
        ),
        migrations.RenameModel(
            old_name='VatCode',
            new_name='VatCodes',
        ),
    ]
