# Generated by Django 3.1.1 on 2020-09-30 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gessol', '0005_auto_20200930_1404'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='suppliers',
            options={'verbose_name': 'supplier', 'verbose_name_plural': 'suppliers'},
        ),
    ]
