# Generated by Django 3.1.1 on 2020-09-30 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gessol', '0006_auto_20200930_1417'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chemprods',
            options={'verbose_name': 'chemical product', 'verbose_name_plural': 'chemical products'},
        ),
        migrations.AlterModelOptions(
            name='chemsubstances',
            options={'verbose_name': 'chemical substance', 'verbose_name_plural': 'chemical substances'},
        ),
        migrations.AlterModelOptions(
            name='hazardpictograms',
            options={'verbose_name': 'hazard pictogram', 'verbose_name_plural': 'hazard pictograms'},
        ),
        migrations.AlterModelOptions(
            name='hazardstatements',
            options={'verbose_name': 'hazard statement', 'verbose_name_plural': 'hazard statements'},
        ),
        migrations.AlterModelOptions(
            name='invoicedetails',
            options={'verbose_name': 'invoice detail', 'verbose_name_plural': 'invoice details'},
        ),
        migrations.AlterModelOptions(
            name='invoiceheaders',
            options={'verbose_name': 'invoice header', 'verbose_name_plural': 'invoice headers'},
        ),
        migrations.AlterModelOptions(
            name='paymentmethods',
            options={'verbose_name': 'payment method', 'verbose_name_plural': 'payment methods'},
        ),
        migrations.AlterModelOptions(
            name='pricelists',
            options={'verbose_name': 'price list', 'verbose_name_plural': 'price lists'},
        ),
        migrations.AlterModelOptions(
            name='svhcsubstances',
            options={'verbose_name': 'svhc substance', 'verbose_name_plural': 'svhc substances'},
        ),
        migrations.AlterModelOptions(
            name='vatcodes',
            options={'verbose_name': 'Vat Code', 'verbose_name_plural': 'Vat Codes'},
        ),
    ]
