# Generated by Django 3.1.1 on 2020-09-30 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gessol', '0007_auto_20200930_1424'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('vat_number', models.CharField(max_length=11)),
                ('cf_number', models.CharField(max_length=16)),
                ('address', models.CharField(max_length=100)),
                ('cap', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=100)),
                ('prov', models.CharField(max_length=10)),
                ('country_state', models.CharField(max_length=10)),
                ('logo', models.ImageField(upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='suppliers',
            name='country_state',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
